# docker-compose.yml
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:5000
    secrets:
      - db_password
      - api_key

secrets:
  db_password:
    file: /opt/mega-app/secrets/db_password
  api_key:
    file: /opt/mega-app/secrets/api_key