# docker-compose.yml
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Backend accessible on port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    secrets:
      - db_password
      - api_key
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows access to host PostgreSQL

secrets:
  db_password:
    file: /opt/mega-app/secrets/db_password
  api_key:
    file: /opt/mega-app/secrets/api_key