# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=mega_organizer;Username=mega_user;Password_FILE=/run/secrets/db_password;SSL Mode=Require
    secrets:
      - db_password
      - api_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  db_password:
    file: /opt/mega-app/secrets/db_password
  api_key:
    file: /opt/mega-app/secrets/api_key