# docker-compose.production.yml
version: '3.8'

services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=https://TODO.com/api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    secrets:
      - db_password
      - api_key
    volumes:
      - ./appsettings.production.json:/app/appsettings.Production.json:ro

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "127.0.0.1:5432:5432"  # Only localhost access

secrets:
  db_password:
    file: /opt/mega-app/secrets/db_password
  api_key:
    file: /opt/mega-app/secrets/api_key

volumes:
  postgres_data:
    driver: local