# docker-compose.yml - Put frontend on host network too
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:5000
    secrets:
      - db_password
      - api_key

secrets:
  db_password:
    file: /opt/mega-app/secrets/db_password
  api_key:
    file: /opt/mega-app/secrets/api_key